AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'MrJohnny'

# Settings
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 10
    Environment:
      Variables:
        ENV: !Ref ENV
        UserPoolId: !Ref UserPoolId
        UserPoolClientId: !Ref UserPoolClientId

# Variable declaration
Parameters:
  ENV:
    Type: String
    Default: "prod"
  UserPoolId:
    Type: String
    Default: "us-east-1_suw91F9jY"
  UserPoolClientId:
    Type: String
    Default: "1uoqd91vkvqdllhjc73anurkqs"

Resources:
  # Api Gateway
  MrJohnny:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Name: MrJohnny

  # Lambda Functions
  RegisterTelephoneNumberFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: register-user.js
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        Signup:
          Type: Api
          Properties:
            RestApiId: !Ref MrJohnny
            Path: /signup
            Method: POST
            # Endpoint available for unauthorized users
            Auth:
              Authorizer: NONE
            RestApiId:
              Ref: MrJohnny


  PreSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async event => {
          event.response = { autoConfirmUser: true };
          return event;
        };

  # User Pool
  UserPoolStaging:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: mrjohnny-user-pool
      LambdaConfig:
        PreSignUp: !GetAtt PreSignupFunction.Arn
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: phone_number
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name:  confirmationCode
          AttributeDataType: String
          Mutable: true
          Required: false

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub mrjohnny-client
      GenerateSecret: false
      UserPoolId: !Ref UserPoolStaging

  IdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      IdentityPoolName: mrjohnny-user-pool
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders: 
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPoolStaging.ProviderName

  # Deployments
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MrJohnny
      Description: Staging deployment

  UserPoolLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PreSignupFunction.Arn
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:cognito-idp:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - userpool/*
