AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "A example REST API build with serverless technology"

Globals:

  # Configuration defaults for all Lambda functions
  Function:
    Runtime: nodejs14.x
    Handler: index.handler
    Timeout: 30
    Tags:
      Application: Serverless API

Resources:

  # Lambda function that prevents the emission of confirmation emails
  PreSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PreSignupFunction
      InlineCode: |
        exports.handler = async event => {
          event.response = { autoConfirmUser: true };
          return event;
        };


