AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
  using Amazon API Gateway.
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs14.x
    Environment:
      Variables:
        ENV:
          Ref: ENV
Parameters:
  ENV:
    Type: String
    Default: prod
  HttpApi:
    Type: String
    Default: SignupFlow
Resources:
  ServerlessApi:
    Type: AWS::Serverless::Api
    ResourceId: zbjfz6bszh
    RestApiId: 9n8r136kre
    EndpointConfiguration:
      Type: REGIONAL
    Properties:
      StageName: Prod
      Cors: '''*'''
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-east-1:411460918332:userpool/us-east-1_eqsRxbA3C
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: '''WWW-Authenticate'''
              Access-Control-Allow-Origin: '''*'''
              WWW-Authenticate: '''Bearer realm="admin"'''
    Metadata:
      SamResourceId: ServerlessApi
  ListBidsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/2b8287cbb44fea81f9f68c88403f0543
      Handler: ListBids.handler
      FunctionName: ListBids
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Role: arn:aws:iam::411460918332:role/service-role/mrjohnny-dynamo-lambda-role
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        lambda-console:blueprint: microservice-http-endpoint
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
      Events:
        Bids:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /list-bids
            Method: GET
    Metadata:
      SamResourceId: ListBidsFunction
