git add ../../html-brand/index.html
git add ../../html-brand/pages/brand-dashboard.html
git add ../../html-brand/pages/brand-landing-page.html
git add ../../html-brand/pages/sign-up.html
git add ../../html-creator/index.html
git add ../../html-creator/pages/creator-dashboard.html
git add ../../html-creator/pages/creator-landing-page.html
git add ../../html-creator/pages/creator_list_view.html
git add ../../html-creator/pages/influencer_video_upload.html
git add ../../html-creator/pages/sign-in.html
git add ../../html-creator/pages/sign-up.html
git add ../../html/index.html
git add ../../html/pages/brand-dashboard.html
git add ../../html/pages/brand-landing-page.html
git add ../../html/pages/creator-dashboard.html
git add ../../html/pages/creator-landing-page.html
git add ../../html/pages/dashboard.html
git add ../../html/pages/influencer_video_upload.html
git add ../../html/pages/landing-page.html
