AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
  using Amazon API Gateway.
Parameters:
  ENV:
    Type: String
    Default: Prod
  BucketName:
    Type: String
    Default: ContentCreatorVideos
Resources:
  ContentCreatorVideos:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          AllowedOrigins:
          - '*'
      BucketName: mrjohnny-upload-contents
    Metadata:
      SamResourceId: ContentCreatorVideos
Outputs:
  S3UploadBucketName:
    Description: S3 bucket for application uploads
    Value:
      Ref: ContentCreatorVideos
