AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
  using Amazon API Gateway.
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
  Function:
    Timeout: 10
    Runtime: nodejs14.x
    Environment:
      Variables:
        ENV:
          Ref: ENV
Parameters:
  ENV:
    Type: String
    Default: Prod
  BucketName:
    Type: String
    Default: mrjohnny-upload-contents
  S3BucketPolicy:
    Type: String
    Default: arn:aws:s3:::mrjohnny-upload-contents
Resources:
  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: '''*'''
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-east-1:411460918332:userpool/us-east-1_eqsRxbA3C
        AddDefaultAuthorizerToCorsPreflight: false
      EndpointConfiguration:
        Type: REGIONAL
        PayloadFormatVersion: '2.0'
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: '''WWW-Authenticate'''
              Access-Control-Allow-Origin: '''*'''
              WWW-Authenticate: '''Bearer realm="admin"'''
    Metadata:
      SamResourceId: ServerlessApi
  LambdaExecRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: mrjohnny-cloudformation-lambda-role
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: MrJohnnyS3ByRegion
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            Resource:
            - arn:aws:s3:::mrjohnny-upload-contents
            - arn:aws:s3:::mrjohnny-upload-contents/*
            - arn:aws:s3:::mrjohnny-logging-for-upload-contents
            - arn:aws:s3:::mrjohnny-logging-for-upload-contents/*
      - PolicyName: MrJohnnyOpenPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            - ec2:DescribeNetworkInterfaces
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            Resource: '*'
      - PolicyName: MrJohnnyClosedPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:Query
            Resource: arn:aws:dynamodb:us-east-1:411460918332:table/*
    Metadata:
      SamResourceId: LambdaExecRole
  ListBrandBidsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/3ee6ffd0dcf3eeec2c287cd9f1c1cb8e
      Handler: ListBids.handler
      FunctionName: ListBrandBids
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
      Events:
        ListBids:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /list-bids
            Method: GET
    Metadata:
      SamResourceId: ListBrandBidsFunction
  PostBrandBidsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/da0562c742885709397d3279cd5bf483
      Handler: PostBid.handler
      FunctionName: PostBrandBids
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
      Events:
        PostBids:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /bids
            Method: POST
    Metadata:
      SamResourceId: PostBrandBidsFunction
  GetBrandBidsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/d1c9b4b7082d2572c4478b223e031e7c
      Handler: GetBid.handler
      FunctionName: GetBrandBids
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
      Events:
        GetBids:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /bids/{id}
            Method: GET
    Metadata:
      SamResourceId: GetBrandBidsFunction
  DeleteBrandBidsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/c3a343f08adcf78427f8188c9477a678
      Handler: DeleteBid.handler
      FunctionName: DeleteBrandBids
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
      Events:
        DeleteBids:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /bids/{id}
            Method: DELETE
    Metadata:
      SamResourceId: DeleteBrandBidsFunction
  CreatorContentSchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/a776c73e8f928c944a6cdd67a27d6392
      Handler: ContentScheduler.handler
      FunctionName: CreatorContentScheduler
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
      Events:
        CreatorScheduler:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /creator_scheduler
            Method: POST
    Metadata:
      SamResourceId: CreatorContentSchedulerFunction
  PutBrandBidsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/858cc7822adc8c09c816384206b6b4ff
      Handler: PutBid.handler
      FunctionName: PutBid
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
      Events:
        PutBid:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /bids/{id}
            Method: PUT
    Metadata:
      SamResourceId: PutBrandBidsFunction
  SignUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/e857a369013f408b7261e57efc68ad8f
      Handler: SignUrl.handler
      FunctionName: SignUrl
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
          UploadBucket:
            Ref: BucketName
      Policies:
      - S3WritePolicy:
          BucketName:
            Ref: S3BucketPolicy
      Events:
        GetSignUrl:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /sign-url/{username}/{filename}
            Method: GET
    Metadata:
      SamResourceId: SignUrlFunction
  BrandSignUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/38e6d81bc633d8159332efa4f7f605b2
      Handler: BrandSignUrl.handler
      FunctionName: BrandSignUrl
      Description: Create brand image upload record in dynamodb and return a sign
        URL for upload / Idempotent - allows for re-submit of image if image fail
        upload
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
          UploadBucket:
            Ref: BucketName
      Policies:
      - S3WritePolicy:
          BucketName:
            Ref: S3BucketPolicy
      Events:
        BrandPutSignUrl:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /brand-sign-url/{username}/{filename}
            Method: PUT
    Metadata:
      SamResourceId: BrandSignUrlFunction
  ContentCreatorSignUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/fc3f20eb2a0a4a62e8b403ba7b4f0f5b
      Handler: ContentCreatorSignUrl.handler
      FunctionName: ContentCreatorSignUrl
      Description: Create creator-content upload record in dynamodb and return a sign
        URL for upload / Idempotent - allows for re-submit of image if image fail
        upload
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
          UploadBucket:
            Ref: BucketName
      Policies:
      - S3WritePolicy:
          BucketName:
            Ref: S3BucketPolicy
      Events:
        CreatorContentSignUrl:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /creator-sign-url/{username}/{filename}
            Method: PUT
    Metadata:
      SamResourceId: ContentCreatorSignUrlFunction
  FetchFileFromS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mrjohnny-deploy/568b28e743a33f024b1a59745095b48f
      Handler: FetchFileFromS3.handler
      FunctionName: FetchFileFromS3
      Description: Retrieve content from S3 and stream
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
          UploadBucket:
            Ref: BucketName
      Policies:
      - S3WritePolicy:
          BucketName:
            Ref: S3BucketPolicy
      Events:
        S3Content:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /content/{key}/{filename}
            Method: GET
    Metadata:
      SamResourceId: FetchFileFromS3Function
  PreSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      FunctionName: MrJohnnyPreSignupFunction
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      InlineCode: "exports.handler = async event => {\n  event.response = { autoConfirmUser:\
        \ true };\n  return event;\n};\n"
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
    Metadata:
      SamResourceId: PreSignupFunction
  MrJohnnyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MrJohnnyAuthFunction
      CodeUri: s3://mrjohnny-deploy/9b1fb5ba6bc30b9f826a69b4569b2600
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
        - LambdaExecRole
        - Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0f666341436597447
        SubnetIds:
        - subnet-0f0ed4f2b3e9c1a75
      Tags:
        service: mrjohny
      Events:
        Signup:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /signup
            Method: POST
            Auth:
              Authorizer: NONE
        Signin:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessApi
            Path: /signin
            Method: POST
            Auth:
              Authorizer: NONE
    Metadata:
      SamResourceId: MrJohnnyAuthFunction
Outputs:
  ApiUrl:
    Description: The target URL of the created API
    Value:
      Fn::Sub: https://${ServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
    Export:
      Name: BidsFlow
